trigger:
- main # Rama principal de tu repositorio

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  azureSubscription: 'serviceconnection-arp'
  appServiceName: 'app-arp-linux-westeu-001'
  resourceGroupName: 'rg-arp-westeu-001'
  projectFolder: 'AzureResourceProbes.API'
  vmImageName: 'ubuntu-latest'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '$(projectFolder)/**/*.csproj'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '$(projectFolder)/**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      projects: '$(projectFolder)/**/*.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: $(azureSubscription)
      appType: 'webAppLinux'
      appName: $(appServiceName)
      package: '$(Build.ArtifactStagingDirectory)/*'
      resourceGroupName: $(resourceGroupName)
